

```{r, load software packages}
rm(list = ls())

#take the working directory otherwise, which should work every time?
if(!exists("location_of_main_folder")){
  location_of_main_folder <- 
    getwd()
}
#paste the name of our functions folder into the path name
location_of_functions_folder <-
  paste0(location_of_main_folder, "/ar_functions_folder/")

#load the function that loads all the libraries and sources
source(paste0(location_of_functions_folder, "load_ar_libraries_and_sources_function.R"))

#paste together the location of the data files - we don't load in the first file, but we need this location for the end
location_of_data_files <-
  paste0(location_of_main_folder, "/ar_data_files_to_load/")

#run the function, pointing it towards the functions folder
load_ar_libraries_and_sources_function(
  location_of_functions_folder=location_of_functions_folder,
  location_of_data_files=location_of_data_files
)

load_ar_files_function(previous_file_name = "file_30",
  parent_directory = location_of_data_files,
  list_of_data_frames_to_load=list("ar_data"))
```



```{r, how much do weight random effects predict height random effects}
ggplot(data=ar_data, aes(x=a_height, y=a_weight)) +
  geom_point() +
  geom_smooth(method="lm")
ggplot(data=ar_data, aes(x=a_bmi, y=a_weight)) +
  geom_point() +
  geom_smooth(method="lm")
ggplot(data=ar_data, aes(x=a_bmi, y=a_height)) +
  geom_point() +
  geom_smooth(method="lm")
```

```{r, how much do weight random effects predict height random effects}
ggplot(data=ar_data, aes(x=b_height, y=b_weight)) +
  geom_point() +
  geom_smooth(method="lm")
ggplot(data=ar_data, aes(x=b_bmi, y=b_weight)) +
  geom_point() +
  geom_smooth(method="lm")
ggplot(data=ar_data, aes(x=b_bmi, y=b_height)) +
  geom_point() +
  geom_smooth(method="lm")
```

```{r, how much do weight random effects predict height random effects}
ggplot(data=ar_data, aes(x=c_height, y=c_weight)) +
  geom_point() +
  geom_smooth(method="lm")
ggplot(data=ar_data, aes(x=c_bmi, y=c_weight)) +
  geom_point() +
  geom_smooth(method="lm")
ggplot(data=ar_data, aes(x=c_bmi, y=c_height)) +
  geom_point() +
  geom_smooth(method="lm")
```





```{r, end of file so save all the listed dataframes into the parent directory}
rm(ar_data)
save_ar_files_function(
  parent_directory=location_of_data_files,
  parent_file="file_31")
Sys.time()
```